# Generated by Django 4.2.15 on 2024-09-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_obejct_detection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Obejct_Detection',
            new_name='Object_Detection',
        ),
    ]
